# 此文件保存的是整个 jekyll 项目的所有配置项，配置好了之后基本就不需要再更改了

# ---------------- #
#   主要配置信息     #
# ---------------- #
baseurl: ""
url: http://www.hao99.cn
date_format: "ordinal"
title: Mr.Zhao的博客
subtitle: "不知道说些什么，先空着吧!"
description: "赵延生的个人博客"
keywords: 赵延生, 软件开发工程师, 软件架构工程师
# 网站网址栏展示的图标
favicon: /favicon.ico
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#     作者信息      #
# ---------------- #
author: 赵延生
# 公司名称 网站
organization: hao99
organization_url: http://www.hao99.cn
github_username: zhaoyansheng163
location: 深圳, 中国
email: 35933019@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /about/
    label: 关于

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# 网页上的开源项目受欢迎程度的排行
repository: zhaoyansheng163/zhaoyansheng163.github.io
